[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/game"
  status = 200

[[redirects]]
  from = "/display"
  to = "/display.html"
  status = 200

[[redirects]]
  from = "/buzz"
  to = "/buzz.html"
  status = 200

[[redirects]]
  from = "/buzz/:team_index"
  to = "/buzz.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"
